import React from 'react';
import { connect } from 'react-redux';
import { ConnectedNav } from './Nav';
import * as mutations from '../store/mutations';
import { HeaderComponent } from './Header';
import { PrivacyComponent } from "./Privacy";
import {Link} from "react-router-dom";


export const TermsComponent = () => (
  <div>
    <ConnectedNav />
    <HeaderComponent />
    <div className="card border-0 flex-grow-0 flex align-items-center justify-content-center">
      <div className="card-body">
        <h5 className="card-title">Terms of Use:</h5>
        <h3>1. WEBSITE DISCLAIMER</h3>
        <p>
          The information provided by PT School Match (“we,” “us” or “our”) on ptschoolmatch.net (the “Site”) and our mobile application is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site or our mobile application. UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR OUR MOBILE APPLICATION OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE AND OUR MOBILE APPLICATION. YOUR USE OF THE SITE AND OUR MOBILE APPLICATION AND YOUR RELIANCE ON ANY INFORMATION ON THE SITE AND OUR MOBILE APPLICATION IS SOLELY AT YOUR OWN RISK.  ALL SALES ARE FINAL.
        </p>
        <h3>2. USE OF SOFTWARE</h3>
        <p>
          Company may make certain software available to you from the Site. If you download software from the Site, the software, including all files and images contained in or generated by the software, and accompanying data (collectively, “Software”) are deemed to be licensed to you by Company, for your personal, noncommercial, home use only. Company does not transfer either the title or the intellectual property rights to the Software, and Company retains full and complete title to the Software as well as all intellectual property rights therein. You may not sell, redistribute, or reproduce the Software, nor may you decompile, reverse-engineer, disassemble, or otherwise convert the Software to a human-perceivable form. All trademarks and logos are owned by Company or its licensors and you may not copy or use them in any manner.
        </p>
        <h3>3. EXTERNAL LINKS DISCLAIMER</h3>
        <p>
          The Site and our mobile application may contain (or you may be sent through the Site or our mobile application) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability or completeness by us. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING. WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.
        </p>
        <h3>4. PROFESSIONAL DISCLAIMER</h3>
        <p>
          The Site cannot and does not contain school advice. The school information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of school advice. THE USE OR RELIANCE OF ANY INFORMATION CONTAINED ON THIS SITE OR OUR MOBILE APPLICATION IS SOLELY AT YOUR OWN RISK.
        </p>
        <h3>5. Privacy Policy</h3>
        <p>
              <Link className="nav-link" to="/privacy">Click Here</Link>
        </p>
        <h3>6. COPYRIGHT</h3>
        <p>
          All contents of Site or Service are: Copyright © 2019 PT School Match. All rights reserved.
        </p>

      </div>
    </div>
  </div>
);
